from . import famille_client
from . import res_partner
from . import transporteur
from . import presentoir
from . import plv
from . import departement
from . import sale_order_line
from . import type_tier
from . import account_invoice
